[workspace]
resolver = "3"
members = [
    "kernel",
    "crates/phoenix-framebuffer",
    "crates/boot-memory",
    "crates/virtual-memory",
    "crates/scheduler",
    "crates/process-model",
]

[package]
name = "phoenixos"
version = "0.0.1"
edition = "2024"
publish = false

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "=0.11.17"
