[workspace]
resolver = "3"
members = [
    "kernel",
    "crates/phoenix-framebuffer",
    "crates/boot-memory",
    "crates/block-storage",
    "crates/virtual-memory",
    "crates/scheduler",
    "crates/process-model",
    "crates/process-manager",
    "crates/service-manager",
    "crates/storage-policy",
    "crates/syscall-abi",
    "crates/capability-model",
    "crates/ipc-model",
    "crates/elf-loader",
    "crates/user-runtime",
    "crates/vfs",
]

[package]
name = "phoenixos"
version = "0.0.1"
edition = "2024"
publish = false

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "=0.11.17"
