[package]
name = "kernel"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
bootloader_api = "=0.11.17"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
linked_list_allocator = "=0.10.6"
phoenix-capability = { path = "../crates/capability-model" }
phoenix-framebuffer = { path = "../crates/phoenix-framebuffer" }
phoenix-memory = { path = "../crates/boot-memory" }
phoenix-process = { path = "../crates/process-model" }
phoenix-scheduler = { path = "../crates/scheduler" }
phoenix-syscall-abi = { path = "../crates/syscall-abi" }
phoenix-vm = { path = "../crates/virtual-memory" }
uart_16550 = "0.8.0"
x86_64 = "0.15.2"
